version: '3'
services:
  app:
    container_name: mauqah
    build:
      context: ./
    volumes:
    - .:/var/www
    ports:
    - "8080:8080"
    environment:
    - APP_ENV=local
    networks:
      - development
networks:
  development:
    external: true
