version: '3'
services:
  app:
    container_name: mauqah
    working_dir: /var/www
    build:
      context: ./
    volumes:
      - .:/var/www
    ports:
      - "80:80"
    environment:
      - APP_ENV=local
  mysql5.7:
    container_name: mysql5.7
    restart: always
    image: mysql:5.7
    ports:
      - 3306:3306
    expose:
      - "3307"
    command: "--max_allowed_packet=1073741824"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: laravel
